# Generated by Django 6.1.1 on 2026-09-03 04:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campus_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên cơ sở')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Ranh giới khuôn viên')),
                ('image_1', models.TextField(blank=True, null=True)),
                ('image_2', models.TextField(blank=True, null=True)),
                ('image_3', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên tòa nhà')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Hình dạng tòa nhà')),
                ('image_1', models.TextField(blank=True, null=True)),
                ('image_2', models.TextField(blank=True, null=True)),
                ('image_3', models.TextField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='map_app.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(verbose_name='Cấp độ tầng')),
                ('name', models.CharField(max_length=255, verbose_name='Tên tầng')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Ranh giới tầng')),
                ('blueprint_url', models.TextField(blank=True, null=True, verbose_name='Link bản vẽ mặt bằng')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='map_app.building')),
            ],
        ),
        migrations.CreateModel(
            name='GreenArea',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên khu vực xanh')),
                ('type', models.CharField(choices=[('grass', 'Thảm cỏ'), ('garden', 'Vườn hoa / Cây cảnh')], max_length=50, verbose_name='Loại mảng xanh')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Diện tích phủ xanh')),
                ('image_1', models.TextField(blank=True, null=True)),
                ('image_2', models.TextField(blank=True, null=True)),
                ('image_3', models.TextField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_areas', to='map_app.campus')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('parking_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên bãi xe')),
                ('capacity', models.IntegerField(blank=True, null=True, verbose_name='Sức chứa dự kiến')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Ranh giới bãi xe')),
                ('image_1', models.TextField(blank=True, null=True)),
                ('image_2', models.TextField(blank=True, null=True)),
                ('image_3', models.TextField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to='map_app.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Tên phòng')),
                ('room_type', models.CharField(choices=[('classroom', 'Phòng học'), ('lab', 'Phòng thực hành / Lab'), ('wc', 'Nhà vệ sinh'), ('office', 'Văn phòng')], max_length=50, verbose_name='Loại phòng')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Tọa độ phòng')),
                ('image_1', models.TextField(blank=True, null=True)),
                ('image_2', models.TextField(blank=True, null=True)),
                ('image_3', models.TextField(blank=True, null=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='map_app.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tree_id', models.AutoField(primary_key=True, serialize=False)),
                ('species', models.CharField(max_length=255, verbose_name='Giống cây')),
                ('health_status', models.CharField(choices=[('good', 'Phát triển tốt'), ('needs_care', 'Cần chăm sóc / Cắt tỉa')], max_length=50, verbose_name='Tình trạng')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Tọa độ gốc cây')),
                ('image_1', models.TextField(blank=True, null=True)),
                ('image_2', models.TextField(blank=True, null=True)),
                ('image_3', models.TextField(blank=True, null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='map_app.campus')),
            ],
        ),
    ]
