# Generated by Django 6.1.1 on 2026-09-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0002_role_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='building/', verbose_name='Hình 1'),
        ),
        migrations.AlterField(
            model_name='building',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='building/', verbose_name='Hình 2'),
        ),
        migrations.AlterField(
            model_name='building',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='building/', verbose_name='Hình 3'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='campus/', verbose_name='Hình 1'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='campus/', verbose_name='Hình 2'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='campus/', verbose_name='Hình 3'),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='greenarea/', verbose_name='Hình 1'),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='greenarea/', verbose_name='Hình 2'),
        ),
        migrations.AlterField(
            model_name='greenarea',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='greenarea/', verbose_name='Hình 3'),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='parking/', verbose_name='Hình 1'),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='parking/', verbose_name='Hình 2'),
        ),
        migrations.AlterField(
            model_name='parkingarea',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='parking/', verbose_name='Hình 3'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='room/', verbose_name='Hình 1'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='room/', verbose_name='Hình 2'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='room/', verbose_name='Hình 3'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='tree/', verbose_name='Hình 1'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='tree/', verbose_name='Hình 2'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='tree/', verbose_name='Hình 3'),
        ),
    ]
