# Generated by Django 6.1.1 on 2026-09-17 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_image_upload_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Tòa nhà', 'verbose_name_plural': 'Tòa nhà'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Tầng', 'verbose_name_plural': 'Các tầng'},
        ),
        migrations.AlterModelOptions(
            name='greenarea',
            options={'verbose_name': 'Mảng xanh', 'verbose_name_plural': 'Mảng xanh'},
        ),
        migrations.AlterModelOptions(
            name='parkingarea',
            options={'verbose_name': 'Bãi xe', 'verbose_name_plural': 'Bãi xe'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Phòng', 'verbose_name_plural': 'Các phòng'},
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Tên cơ sở'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Cấp độ tầng không được là số âm.')], verbose_name='Cấp độ tầng'),
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('campus', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('building', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='greenarea',
            unique_together={('campus', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='parkingarea',
            unique_together={('campus', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('floor', 'name')},
        ),
    ]
